tag: terminal
-
# tags should be activated for each specific terminal in the respective talon file

lisa [dir] [<user.text>]: user.terminal_list_directories(text or "")
lisa all: user.terminal_list_all_directories()
katie [dir] [<user.text>]: user.terminal_change_directory(text or "")
katie root: user.terminal_change_directory_root()
katie (up | back): user.terminal_change_directory("..")
look now: insert('l \n')
look look now: insert('ll \n')
move [<user.text>]: insert('mv ')
copy [<user.text>]: insert('cp ')
open [<user.text>]: insert('open ')
powder [<user.text>]: insert('pwd ')
remove [<user.text>]: insert('rm ')
ugly [<user.text>]: insert('uglr ')
winner [<user.text>]: insert('vim ')
grab [<user.text>]: insert('grep ')
find [<user.text>]: insert('find ')
find name [<user.text>]: insert('find -name ')
hour sink [<user.text>]: insert('rsync -avuP ')
python [<user.text>]: insert('py ')
python now: insert('py \n')
go <user.system_path>: insert('cd "{system_path}"\n')
path <user.system_path>: insert('"{system_path}"')
clear screen: user.terminal_clear_screen()
run last: user.terminal_run_last()
rerun [<user.text>]: user.terminal_rerun_search(text or "")
rerun search: user.terminal_rerun_search("")
kill all: user.terminal_kill_all()

hash top [<user.text>]: insert('htop ')
make directory [<user.text>]: insert('mkdir ')
secure shell [<user.text>]: insert('ssh ')
tee mux [<user.text>]: insert('tmux ')
